### ISSUE TITLE
How to define custom rule?

### ISSUE THREAD

**Issue by JinSeoung-Oh** [whyhow-ai/rule-based-retrieval#2]
First of all, thank you for your excellent work. 
Recently, I've been wanting to create a RAG for insurance terms, and I think using your excellent model would be very helpful. 
However, I have a few questions. 
Firstly, I'd like to know about the defined rules. I've looked through the code but couldn't find where the existing rules are defined. When dealing with rule-based models, there's often a need to define custom rules, so I'm asking about that. 
I would appreciate it if you could also explain how to define custom rules. 
Additionally, if possible, it would be helpful to know the format of the input data. I'm curious about what information the input data should contain.

Thanks!

**Comment by recchris** [comment]
Hi @JinSeoung-Oh. A few things that might help you here:

1. If you would like to add another attribute to the Rules type, you can extend the Rule class in `src/whyhow/rag.py` to include other types of metadata that you can then use to build metadata filters. Be sure to also update `to_filter()` to account for new types of filters you're adding. Please also check the [Pinecone docs](https://docs.pinecone.io/guides/data/filtering-with-metadata) to ensure their metadata filters support your use case.
2. To add a new rule to your ruleset, all you need to do is add a Rule (with relevant attributes) to a list of rules and pass those in to your query
```
rules = [
    Rule(
        filename="harry_potter_book_1.pdf",
        page_numbers=[21, 22, 23]
    ),
    Rule(
        filename="harry_potter_book_2.pdf",
        page_numbers=[151, 152, 153, 154]
    )
]

result = client.query(
    question=question,
    index=index,
    namespace=namespace,
    rules=rules,
    top_k=top_k,
)
```

Re: input data format, the package currently supports PDF documents by default, but you can extend it to support other types of files. Check out `src/whyhow/processing.py`. Here, we're leveraging Langchain's PyPDFLoader and RecursiveCharacterTextSplitter to load, split, and chunk raw unstructured documents. Langchain offers various other [document loaders](https://python.langchain.com/docs/modules/data_connection/document_loaders/) that you can plug + play, or you can write your own.

Please reach out if you have any other questions. I encourage you to create a fork and send a PR. We're happy to review + help. Thx!

**Comment by JinSeoung-Oh** [comment]
@recchris Thank you for your kind response! I'll try it once according to your advice. I hope you have a great day!
