### ISSUE TITLE
Add Qdrant vector store support

### ISSUE THREAD

**Issue by Anush008** [whyhow-ai/rule-based-retrieval#9]
Hey all 👋.

I wanted to know if I can contribute a feature to add Qdrant - https://qdrant.tech/ as a supported vector store in the project.

**Comment by recchris** [comment]
Thanks for reaching out @Anush008. Sure, that would be great! For context, check out this PR from the Milvus team - https://github.com/whyhow-ai/rule-based-retrieval/pull/6. Adding Qdrant should follow roughly the same process. Feel free to submit a PR and we can take a look. Please also feel free to set time [here](https://calendly.com/whyhow-chris/30min) if you'd like to discuss.
